server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://localhost:8081
          predicates:
            - Path=/payments/**
        - id: ticket
          uri: http://localhost:8082
          predicates:
            - Path=/tickets/**
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /guestManagementPages/**
        - id: book
          uri: http://localhost:8084
          predicates:
            - Path=/books/**
        - id: alarm
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/payments/**
        - id: ticket
          uri: http://room:8080
          predicates:
            - Path=/rooms/**
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /guestManagementPages/**
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/**
        - id: alarm
          uri: http://alarm:8080
          predicates:
            - Path=/notifications/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
