apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: c2xka2Zqc2tsZGZqc2Rsa2ZqbHNrZnNmamxzZmpscwo=
  database-name: eW91YXJlbW90aGVybWF3ZXdyd2Vycm4K
  user-username: eW91YXJlbW90aGVybWF3ZXdyMjMyMzJ3ZXJybgo=
  user-password: eW91YXJlbW90aGVybWFuCg==